<a href="https://colab.research.google.com/github/cownow4425/Python-for-AI/blob/master/Numpy/3_numpy_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
test_example = np.array([[1,2,3],[4.5,5,6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
test_example[0][2]

3

In [ ]:
test_example[0,2]

3

In [ ]:
test_example[0,0] = 10 #matrix 0,0에 10 할당
test_example

array([[10,  2,  3],
       [ 4,  5,  6]])

In [ ]:
test_example[1,2] = 5
test_example[1,2]

5

slicing


In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[:, 2:]) #전체 row의 2열 이상
print(a[1, 1:3]) #1 row의 1열 ~ 2열
print(a[1:3]) #1 row ~ 2row 전체

[[ 3  4  5]
 [ 8  9 10]]
[7 8]
[[ 6  7  8  9 10]]


In [ ]:
b = np.arange(100).reshape(10, 10)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
b[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])