<a href="https://colab.research.google.com/github/cownow4425/Python-for-AI/blob/master/Numpy/4_numpy_creation_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arange

In [ ]:
list(range(0, 10, 3))

[0, 3, 6, 9]

In [ ]:
type(list(range(30)))

list

In [ ]:
#range: List의 range와 같은 효과
#integer로 0부터 29까지 배열추출
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
np.arange(0, 10, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.arange(0, 5, 0.5) #floating point도 표시가능함

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
np.arange(30).reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

ones, zeros & empty

In [ ]:
#10 - zero vector 생성
np.zeros(shape=(10, ), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [ ]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(shape=(10, ), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [ ]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.empty(shape=(10, ), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [ ]:
np.empty((10, 5))

array([[4.67455670e-310, 4.67455498e-310, 1.88733077e-321,
                    nan, 1.67416765e+243],
       [3.48640147e+228, 5.29877244e+180, 2.28354977e+243,
        4.61984436e+281, 1.05118620e-153],
       [7.50590667e+247, 9.29229276e+199, 2.87686160e+159,
        2.74865973e+214, 4.59239265e-072],
       [4.40571859e-085, 4.61985817e+281, 1.14737978e+253,
        2.38345023e+180, 4.59239265e-072],
       [6.01430546e+175, 4.61988042e+281, 2.26602614e+188,
        3.94357083e+180, 4.59240550e-072],
       [1.28140136e+213, 1.48861373e+195, 5.08602467e+231,
        7.35167791e+223, 1.96960056e-153],
       [7.49229529e+247, 1.28624552e+248, 2.75792455e+212,
        9.29600696e+242, 1.38031622e+267],
       [1.31101443e-259, 8.38916524e+217, 5.03872425e+175,
        1.14738044e+253, 4.99955025e+228],
       [2.46928934e-027, 1.99432437e+209, 1.22718737e+266,
        1.57264490e-052, 8.38916524e+217],
       [5.03872425e+175, 2.66331938e-260, 2.05131673e+161,
        2.05791651e-027

In [ ]:
test_matrix = np.arange(100).reshape(5, -1)

In [ ]:
test_matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [ ]:
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

eye, identity & digonal

In [ ]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [ ]:
np.eye(N=3, M=5, k=1, dtype=np.int8)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=int8)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
matrix = np.arange(12).reshape(3, 4)

In [ ]:
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.diag(matrix, k=1)

array([ 1,  6, 11])

numpy.random

In [ ]:
np.random.normal(0, 1, 10).reshape(2, 5)

array([[ 0.51812243,  0.07690958, -1.24894677, -0.59162415, -1.18776272],
       [-1.4236238 , -0.75781118, -0.50732066, -0.27021677,  0.39710611]])

In [ ]:
np.random.exponential(scale=2, size=(2, 5))

array([[3.48968732e-04, 1.04478310e+00, 4.01830648e+00, 5.93380306e+00,
        2.57910711e-02],
       [3.60790343e+00, 4.10980611e-01, 3.33309861e+00, 3.88968589e-01,
        1.55328014e+00]])