<a href="https://colab.research.google.com/github/cownow4425/Python-for-AI/blob/master/Numpy/6_numpy_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Array operations

In [ ]:
test_a = np.array([[1,2,3],[4,5,6]], float)

In [ ]:
test_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
test_a + test_a #Matrix + Matrix 연산

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [ ]:
test_a - test_a #Matrix - Matrix 연산

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
test_a * test_a #Matrix 내 element들 간 같은 위치에 있는 값들끼리 연산(Element-wise operation)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [ ]:
matrix_a = np.arange(1, 13).reshape(3, 4)

In [ ]:
matrix_a - matrix_a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

dot product

In [ ]:
test_a = np.arange(1, 7).reshape(2, 3)
test_b = np.arange(7, 13).reshape(3,2)

In [ ]:
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
test_b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [ ]:
test_a = np.arange(1, 7).reshape(2,3)

In [ ]:
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

broadcasting

In [ ]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

In [ ]:
test_matrix

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
test_matrix - scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [ ]:
test_matrix * 5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [ ]:
test_matrix **2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [ ]:
test_matrix = np.arange(1, 13).reshape(4, 3)
test_vector = np.arange(10, 40, 10)

In [ ]:
test_vector

array([10, 20, 30])

In [ ]:
test_vector.reshape(-1, 3).T + test_vector

array([[20, 30, 40],
       [30, 40, 50],
       [40, 50, 60]])

In [ ]:
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

numpy performance

In [ ]:
def scalar_vector_product(scalar, vector):
  result=[]
  for value in vector:
    result.append(scalar * value)
  return result

iternation_max = 100000000

vector = list(range(iternation_max))
scalar = 2

%timeit scalar_vector_product(scalar, vector) #for loop을 이용한 성능

1 loop, best of 5: 13.3 s per loop


In [ ]:
%timeit [scalar * value for value in range(iternation_max)] #list comprehension을 이용한 성능

1 loop, best of 5: 11 s per loop


In [ ]:
%timeit np.arange(iternation_max) * scalar #numpy를 이용한 성능

1 loop, best of 5: 283 ms per loop
