<a href="https://colab.research.google.com/github/cownow4425/Python-for-AI/blob/master/7_numpy_comparison.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

all & any

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a < 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [ ]:
a < 1

array([ True, False, False, False, False, False, False, False, False,
       False])

In [ ]:
a < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
np.all(a < 10)

True

In [ ]:
np.any(a > 5)

True

comparison operation

In [ ]:
test_a = np.array([1,3,0], float)
test_b = np.array([5,2,1], float)

In [ ]:
test_a > test_b

array([False,  True, False])

In [ ]:
(test_a > test_b).any()

True

In [ ]:
(test_a > test_b).all()

False

In [ ]:
a = np.array([1,3,0], float)
a > 0

array([ True,  True, False])

In [ ]:
a < 3

array([ True, False,  True])

In [ ]:
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [ ]:
b =np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [ ]:
c = np.array([False, True, False], bool)
c

array([False,  True, False])

In [ ]:
np.logical_or(b, c)

array([ True,  True,  True])

np.where

In [ ]:
a

array([1., 3., 0.])

In [ ]:
np.where(a > 2) #index 반환

(array([1]),)

In [ ]:
np.where(a < 3)

(array([0, 2]),)

In [ ]:
np.where(a < 3)[0]

array([0, 2])

In [ ]:
np.where(a < 3, 3, 2) #where(condition, TRUE, FALSE)

array([3, 2, 3])

In [ ]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.where(a > 10)

(array([6, 7, 8, 9]),)

In [ ]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [ ]:
np.isfinite(a)

array([ True, False, False])

armax & argmin

In [ ]:
a = np.array([1,2,4,5,8,78,23,3])
a

array([ 1,  2,  4,  5,  8, 78, 23,  3])

In [ ]:
a.argsort()

array([0, 1, 7, 2, 3, 4, 6, 5])

In [ ]:
a.argsort()[::-1]

array([5, 6, 4, 3, 2, 7, 1, 0])

In [ ]:
np.argmax(a)

5

In [ ]:
np.argmin(a)

0

In [ ]:
a = np.array([[1,2,4,7], [9,88,6,45], [9,76,3,4]])
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [ ]:
np.argmax(a, axis=1)

array([3, 1, 1])

In [ ]:
np.argmin(a, axis=0)

array([0, 0, 2, 2])