<a href="https://colab.research.google.com/github/cownow4425/Python-for-AI/blob/master/Numpy/8_numpy_boolean_fancy_index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

boolean index

In [ ]:
test_array = np.array([1,4,0,2,3,8,9,7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [ ]:
test_array.shape

(8,)

In [ ]:
(test_array > 3).shape

(8,)

In [ ]:
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [ ]:
condition = test_array < 3

In [ ]:
test_array[condition]

array([1., 0., 2.])

fancy index 

In [ ]:
a = np.array([2,4,6,8], float)
cond = np.array([1,1,1,2,1,1,1,3])

In [ ]:
a.take(cond)

array([4., 4., 4., 6., 4., 4., 4., 8.])

In [ ]:
a[cond]

array([4., 4., 4., 6., 4., 4., 4., 8.])

In [ ]:
a = np.array([[1,4],[9,16]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)
a[b, c] #b를 row index, c를 column index로 변환하여 표시함

array([ 1.,  4., 16., 16.,  4.])

In [ ]:
a = np.array([[1,4],[9,16]], float)
a[b]

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 9., 16.],
       [ 9., 16.],
       [ 1.,  4.]])